# Generated by Django 4.1 on 2025-01-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p5site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='has_buttons',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
