# Generated by Django 4.1 on 2025-04-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p5site', '0002_sketch_has_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='old_3d',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
